options:
  spellcheck: true
editor:
  inputStyle: contenteditable
  spellcheck: true
# hexo-admin authentification
admin:
  username: benwinding
  password_hash: $2a$10$lSb/3kTaYUsn.GO8FzE8huEXyQnWdtKdUK51F7EkRaofBkoYGMls6
  secret: monkey goat elephant kiteboard